Добавлены новые сокращения
MarshalX/yandex-music-api pull request #354
Opened 2020-07-13 19:51 UTC by glebliutsko

| Класс      | Сокращения                  |
|------------|-----------------------------|
| TrackId    | fetch_track                 |
| PlaylistId | playlist_id, fetch_playlist |
| Search     | next_page                   |
| QueueItem  | fetch_queue                 |
| Queue      | get_current_track           |

2021-02-01 16:04 UTC, MarshalX requested changes

2021-02-01 16:04 UTC, MarshalX commented on yandex_music/landing/track_id.py
> +        def get_track_id():
Это же можно вынести в проперти текущего класса, а не делать какой-то вложенной функцией

2021-02-01 16:04 UTC, MarshalX commented on yandex_music/search/search.py
> +    def next_page(self, *args, **kwargs):
Тогда нужно добавить и prev_page

2021-02-01 16:04 UTC, MarshalX commented on yandex_music/search/search.py
> +    def next_page(self, *args, **kwargs):
А лучше добавить общий метод, который будет шорткатом для получения определенной страницы (из аргумента функции с дефолтом на первую или нулевую, смотря от какой цифры счет), а уже два других метода (next и prev) будут его использовать передавая только номер страницы `self.page +- 1`

2021-02-05 12:52 UTC, glebliutsko commented on yandex_music/landing/track_id.py
> +        return self.client.tracks(get_track_id(), *args, **kwargs)[0]
> И при такой реализации должна быть возможность принудительно сделать запрос, несмотря на кеш. Какой-нибудь refresh_track или чёт типа того. Ещё можно bool аргумент добавить к методу. `force=True`

Тогда может добавить аргумент к остальным методам, кэширующим что-либо. [Например тут ](https://github.com/MarshalX/yandex-music-api/blob/development/yandex_music/track_short.py#L65)

2021-02-05 13:38 UTC, MarshalX commented on yandex_music/landing/track_id.py
> +        return self.client.tracks(get_track_id(), *args, **kwargs)[0]
> > И при такой реализации должна быть возможность принудительно сделать запрос, несмотря на кеш. Какой-нибудь refresh_track или чёт типа того. Ещё можно bool аргумент добавить к методу. `force=True`
> 
> Тогда может добавить аргумент к остальным методам, кэширующим что-либо. [Например тут ](https://github.com/MarshalX/yandex-music-api/blob/development/yandex_music/track_short.py#L65)

+

2021-02-05 14:37 UTC, glebliutsko commented
Продолжение #407

2021-02-05 14:37 UTC, closed without merging