Примеры: плеер плейлистов
MarshalX/yandex-music-api pull request #378
Opened 2020-11-20 18:08 UTC by OwnageIsMagic

использует VLC по умолчанию, но можно поменять через аргументы

2020-11-21 21:57 UTC, MarshalX requested changes
Спасибо, но есть куда улучшить. Не хотите уйти от `print()` на `logging` (модуль стандатрный). Убрать закомментированный код и добавить комментарии к коду (на русском)? Чутка порефакторить тоже не мешало бы. Остальные нюансы прокомментировал отдельно

2020-11-21 21:57 UTC, MarshalX commented on examples/player.py
> +    tracks = client.users_likes_tracks()
Вот тут можно инанче получить лайкнутые треки пользователя и тогда будут полные версии треков, а не сокращенный (я про объекты и их поля)

2020-11-21 21:57 UTC, MarshalX commented on examples/player.py
> +            track = short_track.track if short_track.track else short_track.fetchTrack()
Если иначе получить лайки, то такого делать не придется. Более того, если оставить старое получение, то текущий код порадит N запросов, где N - количество треков. Можно свести к одному

2020-11-21 21:57 UTC, MarshalX commented on examples/player.py
> +parser = argparse.ArgumentParser()
было бы круто все аргументы и запуск уснести под `if __name__ == '__main__'`, а основной код в какую-нибудь функцию аля main()

2020-11-21 21:57 UTC, MarshalX commented on examples/player.py
> +    pass
забыли убрать `pass`

2020-11-21 21:57 UTC, MarshalX commented on examples/player.py
> +    playlist = next(p for p in user_playlists if p.title == args.playlist_name)
Если плейлист не будет найден, то выпадет исключение, которое никто не обработает

2020-11-21 21:57 UTC, MarshalX commented on examples/player.py
> +            print(f'Now playing {i + 1}/{total_tracks}:',
как насчет разбить на 3 вызова print(), но у первых двух будет `end=''`?

2020-11-21 21:57 UTC, MarshalX commented on examples/player.py
> +            album_dir = Path(f'{track.albums[0].title}_{track.albums[0].id}')
Очень странно, что при выводе в консоль мы обрабатывали всех исполнителей и альбомы, а в папках используем только первого забывая про остальных

2020-11-22 01:18 UTC, OwnageIsMagic commented on examples/player.py
> +parser = argparse.ArgumentParser()
а зачем если экспортов нет? только лишний отступ
+ я это сюда выложил для примера и удобно когда всё линейно сверху вниз идёт

2020-11-22 01:23 UTC, OwnageIsMagic commented on examples/player.py
> +    pass
А токен всегда 39? я не проверял
я помню как я специально для себя его добавил как _визуальный_ аналог `break` из этого большого `if` работы с токеном
```suggestion
```

2020-11-22 01:27 UTC, OwnageIsMagic commented on examples/player.py
> +            album_dir = Path(f'{track.albums[0].title}_{track.albums[0].id}')
я надеюсь на то что метаданные трека стабильные и авторы не будут меняться/перемешиваться и не делаю очень длинные имена папок
по хорошему их надо ещё экранировать от плохих сиволов
безопаснее всего использовать только ид, но так читаемость человеком пропадает

2020-11-22 01:27 UTC, OwnageIsMagic commented on examples/player.py
> +            # sys.exc_info()
```suggestion
```

2020-11-22 01:32 UTC, OwnageIsMagic commented on examples/player.py
> +    tracks = client.users_likes_tracks()
А как иначе?

2020-11-22 01:38 UTC, OwnageIsMagic commented on examples/player.py
> +            track = short_track.track if short_track.track else short_track.fetchTrack()
у меня 2к лайков, и обычно я не успеваю прослушать их все
а тут у человека https://github.com/MarshalX/yandex-music-api/issues/360#issue-671598704 10к треков
я не думаю что он захочет ждать пока загрузятся гигабайты жсона
можно заменить например на батч по 10, но зачем усложнять пример?

2020-11-22 01:43 UTC, OwnageIsMagic commented on examples/player.py
> +    playlist = next(p for p in user_playlists if p.title == args.playlist_name)
```suggestion
    playlist = next(p for p in user_playlists if p.title == args.playlist_name)
    if playlist == None:
        print(f'playlist "{args.playlist_name}" not found')
        sys.exit(1)
```

2020-11-22 01:45 UTC, OwnageIsMagic commented on examples/player.py
> +    total_tracks = len(tracks.tracks)
тут столкнулся с тем что у `Track`/`ShortTrack` есть `__iter__ `но нет `__len__`

2020-11-22 01:45 UTC, OwnageIsMagic commented on examples/player.py
> +# sys.path.append('../yandex-music-api/')
```suggestion
```

2020-11-22 01:46 UTC, OwnageIsMagic commented on examples/player.py
> +# user_parser = sub_parser.add_parser('user')
```suggestion
```

2020-11-22 01:46 UTC, OwnageIsMagic commented on examples/player.py
> +parser.add_argument('--playlist-name', # required=True,
```suggestion
parser.add_argument('--playlist-name',
```

2020-11-22 01:49 UTC, OwnageIsMagic commented on examples/player.py
> +                f"[{'|'.join(a.title for a in track.albums)}]", '~', track.title)
```suggestion
            print(f'Now playing {i + 1}/{total_tracks}: ', end='')
            print('|'.join(a.name for a in track.artists), end='')
            print(f" [{'|'.join(a.title for a in track.albums)}]", '~', track.title)
```

2020-11-22 01:50 UTC, OwnageIsMagic commented on examples/player.py
> +
```suggestion
```

2020-11-22 02:04 UTC, OwnageIsMagic commented
>  уйти от `print`

`logging` для логов, а тут везде вывод в `stdout`

> добавить комментарии к коду (на русском)

уфф

> Убрать закомментированный код

убрал

2020-11-22 02:14 UTC, OwnageIsMagic commented
хотел ещё добавить плейлист дня, но не разобрался как вытянуть из него список треков

2020-11-22 11:20 UTC, MarshalX commented on examples/player.py
> +    tracks = client.users_likes_tracks()
Плейлист "Мне нравится" всегда имеет id = 3)

2020-11-22 11:21 UTC, MarshalX commented on examples/player.py
> +            track = short_track.track if short_track.track else short_track.fetchTrack()
Там будут мегабайты джойсона, но, согласен. Усложнее

2020-11-22 11:23 UTC, MarshalX commented on examples/player.py
> +    total_tracks = len(tracks.tracks)
угу, можно допилить в рамках шорткатов, т.е. удобств в целом

2020-11-22 11:25 UTC, MarshalX commented on examples/player.py
> +parser = argparse.ArgumentParser()
> хотел ещё добавить плейлист дня, но не разобрался как вытянуть из него список треков

из лендинга пользователя находим generated playlists, а потом, если там нет шортката на получение обычного плейлиста, то получаем плейлист по kind и owner. Эти данные есть у generated playlist

2020-11-22 11:25 UTC, MarshalX commented
> хотел ещё добавить плейлист дня, но не разобрался как вытянуть из него список треков

из лендинга пользователя находим generated playlists, а потом, если там нет шортката на получение обычного плейлиста, то получаем плейлист по kind и owner. Эти данные есть у generated playlist

2020-11-22 11:28 UTC, MarshalX requested changes

2020-11-22 11:28 UTC, MarshalX commented on examples/player.py
> +    if playlist == None:
Я конечно могу ошибаться, но считаю, что next() кинет исключение StopIter... Если мы хотим проверять на None, то в next() вторым аргументом надо указать default value

2020-11-22 12:46 UTC, OwnageIsMagic commented on examples/player.py
> +    tracks = client.users_likes_tracks()
Хардкодить айдишники говоришь?

2020-11-22 12:53 UTC, OwnageIsMagic commented on examples/player.py
> +    playlist = next(p for p in user_playlists if p.title == args.playlist_name)
```suggestion
    playlist = next((p for p in user_playlists if p.title == args.playlist_name), None)
```

2020-11-22 13:20 UTC, OwnageIsMagic commented on examples/player.py
> +parser.add_argument('--print-args', action='store_true')
```suggestion
parser.add_argument('--print-args', action='store_true',
                    help='print arguments (including default values) and exit')
```

2020-11-22 13:20 UTC, OwnageIsMagic commented on examples/player.py
> +            album_dir = Path(f'{track.albums[0].title}_{track.albums[0].id}')
например https://music.yandex.ru/album/4632882/track/28821181
`"C:/Program files (x86)/Yandex Music Terminal Client/.YMCache/Алексей Рыбников_12345678, Мила Берлинская_12345678, Игорь Капитанников_12345678, Людмила Берлинская_12345678, Игорь Капитанников_12345678/Звёзды Ретро ФМ_12345678/Я тебе, конечно, верю_12345678".length === 255`
Что у некотрых программ на Windows вызовет проблемы

2020-11-22 13:23 UTC, OwnageIsMagic commented
Интересно, GitHub уважает `!fixup`?

2020-11-24 07:23 UTC, MarshalX commented on examples/player.py
> +    tracks = client.users_likes_tracks()
Именно

2020-11-24 07:28 UTC, MarshalX commented
> уфф

так что?) Я не прошу весь код, а только участки с использованием библиотеки

2020-11-24 19:42 UTC, OwnageIsMagic commented on examples/player.py
> +                         help='name of user playlist')
```suggestion
                    help='name of user playlist')
```

2020-11-24 19:48 UTC, OwnageIsMagic commented
<img src="https://user-images.githubusercontent.com/10534634/100143568-912c9900-2ea6-11eb-9e58-d911415254e7.png" width="377" height="156" />

2021-02-01 11:17 UTC, merged