Пофиксил выбор настроек радио
MarshalX/yandex-music-api pull request #390
Opened 2021-01-03 17:25 UTC by superdima05

Запрос на смену надо отправлять на https://api.music.yandex.net/rotor/station/{station}/settings3 вместо https://api.music.yandex.net/rotor/station/{station}/settings2. 

Также data запроса должна содержать type. Клиент Yandex.Music на iOS передавал type: rotor

2021-01-03 22:06 UTC, MarshalX commented
Тип точно один? Уверены, что нет других? Может стоит вынести в аргумент метода?

2021-01-03 22:30 UTC, superdima05 commented
Я встретил только 1 тип. Но в ошибке, когда я указал неправильный тип, было сказано, что есть два типа.

2021-01-04 12:51 UTC, MarshalX commented
Выход надо поиграться со вторым типом и понять что за он. Вынести в аргумент, в документации указать возможные варианты. По умолчанию сделать `rotor`

2021-01-06 16:26 UTC, superdima05 commented
Добавил типы.

2021-01-08 19:02 UTC, MarshalX requested changes

2021-01-08 19:02 UTC, MarshalX commented on yandex_music/client.py
> +            Доступные значения для `_type`: `rotor`, `generative`
Раз уж всё равно придётся поправить, то можно доставить точку в конец 😂

2021-01-08 19:02 UTC, MarshalX commented on yandex_music/client.py
> +            _type (:obj:`str`): Тип.
Не удалось выяснить тип чего? Что такое настройки с типом generative?

2021-01-08 19:04 UTC, superdima05 commented on yandex_music/client.py
> +            _type (:obj:`str`): Тип.
Изучая клиент на iOS, я не понял для чего нужен второй тип.

2021-01-18 15:41 UTC, superdima05 commented
Изменил с _type на type_

2021-01-19 08:31 UTC, MarshalX approved these changes

2021-01-19 08:34 UTC, merged

2021-01-19 08:34 UTC, MarshalX commented
Спасибо!