__iter__ и __len__ для классов представляющих список каких-либо объектов
MarshalX/yandex-music-api pull request #405
Opened 2021-01-31 14:01 UTC by glebliutsko

2021-01-31 17:30 UTC, MarshalX requested changes
А тесты?)

2021-02-01 11:29 UTC, glebliutsko commented
> А тесты?) 

А разве нужны? У `trackShort` нету вроде тестов для __len__ и __iter__.

2021-02-01 12:55 UTC, MarshalX commented
> > А тесты?)
> 
> А разве нужны? У `trackShort` нету вроде тестов для `__len__` и `__iter__`.

Значит и туда добавить надо. Можно в рамках этого ПРа)

2021-02-01 15:26 UTC, MarshalX commented on tests/test_tracks_similar.py
> +    def test_iter(self, similar_tracks):
Почему лист? Откуда? Разве мы не можем сравнить итераторы? Итератор от листа должен быть равен итератору от нашего объекта. Больше и не надо. Мы проверяем реализацию iter, что берём по нужному полю итератор для объекта

2021-02-01 15:29 UTC, MarshalX requested changes
А для методов что уже были не добавлял тесты?

2021-02-01 15:29 UTC, MarshalX commented on tests/test_tracks_similar.py
> +        assert list(similar_tracks) == similar_tracks.similar_tracks
Почему лист? Откуда? Разве мы не можем сравнить итераторы? Итератор от листа должен быть равен итератору от нашего объекта. Больше и не надо. Мы проверяем реализацию iter, что берём по нужному полю итератор для объекта

2021-02-01 15:31 UTC, MarshalX commented on tests/test_tracks_similar.py
> +        assert list(similar_tracks) == similar_tracks.similar_tracks
Это могут быть два разных объекта конечно которые непонятно как сравниваются. Если сравнение будет невозможно, то оставим лист что ль

2021-02-01 16:03 UTC, glebliutsko commented on tests/test_tracks_similar.py
> +        assert list(similar_tracks) == similar_tracks.similar_tracks
Типо так?
```python
def test_iter(self, artist_tracks):
    assert iter(artist_tracks) == iter(artist_tracks.tracks)
```

2021-02-01 16:11 UTC, glebliutsko commented
> А для методов что уже были не добавлял тесты?

Каких методов? Я чет не догоняю

2021-02-01 16:11 UTC, glebliutsko commented
Сори, закрыл случано

2021-02-01 16:12 UTC, MarshalX commented
> > А тесты?)
> 
> А разве нужны? У `trackShort` нету вроде тестов для `__len__` и `__iter__`.

Вот этих

2021-02-01 16:14 UTC, glebliutsko commented
А, там не у `trackShort`, а у `TracksList` не было. В `TracksList` добавил

2021-02-01 16:21 UTC, MarshalX commented on tests/test_tracks_similar.py
> +        assert list(similar_tracks) == similar_tracks.similar_tracks
Ну собсна да, разные объекты, ок, тогда оставляем list()

2021-02-01 16:22 UTC, MarshalX commented on yandex_music/artist/artist_albums.py
> +    def __len__(self):
забыл хинт что возвращает, хотя конечно идея и без этого поймет

2021-02-01 16:22 UTC, MarshalX commented on yandex_music/track/tracks_similar.py
> +    def __getitem__(self, item):
забыл хинт

2021-02-01 17:01 UTC, MarshalX approved these changes

2021-02-01 17:01 UTC, merged