Сокращения
MarshalX/yandex-music-api pull request #407
Opened 2021-02-05 14:36 UTC by glebliutsko

Продолжение #354

2021-02-05 15:56 UTC, MarshalX requested changes
Меня смущает идея вводить кеша на сокращения. Может вовсе отказаться и пусть за этим следят те, кто использует библиотеку?

2021-02-05 15:56 UTC, MarshalX commented on yandex_music/landing/track_id.py
> +        if self.track_id:
```
track_id = self.id 
if self.track_id:
    track_id = self.track_id
```

?

2021-02-05 15:56 UTC, MarshalX commented on yandex_music/landing/track_id.py
> +    def fetch_track(self, force: bool = True, *args, **kwargs) -> 'Track':
Вместо `force` используем `withCache`. По умолчанию True.

2021-02-05 15:56 UTC, MarshalX commented on yandex_music/playlist/playlist_id.py
> +    def fetch_playlist(self, *args, **kwargs):
Кеширование?

2021-02-05 15:56 UTC, MarshalX commented on yandex_music/queue/queue_item.py
> +    def fetch_queue(self, *args, **kwargs) -> Optional['Queue']:
Кеширование?

2021-02-05 15:56 UTC, MarshalX commented on yandex_music/search/search.py
> +    def other_page(self, page: int, *args, **kwargs) -> Optional['Search']:
get_page() ?

2021-02-05 15:56 UTC, MarshalX commented on yandex_music/search/search.py
> +    def next_page(self, *args, **kwargs) -> Optional['Search']:
А в получении страницы что по кешам? Меня начинает это смущать

2021-02-05 15:58 UTC, glebliutsko commented
> Меня смущает идея вводить кеша на сокращения. Может вовсе отказаться и пусть за этим следят те, кто использует библиотеку?

Меня это тоже смущает, но в подобных методах кеш был сделан, вот я и сделал)

Возможно конечно надо удалить

2021-02-05 16:06 UTC, MarshalX commented
> > Меня смущает идея вводить кеша на сокращения. Может вовсе отказаться и пусть за этим следят те, кто использует библиотеку?
> 
> Меня это тоже смущает, но в подобных методах кеш был сделан, вот я и сделал)
> 
> Возможно конечно надо удалить.
> Ну так оставляем, и я фикшу все связанное с кешом, или удаляем?

Удаляй везде где есть. Те, кого заботит оптимизация по запросам учтут моментально. А те, кто получает в цикле каждый трек плейлиста отдельно, вместо формирования списка ИДшников и выполнения одного запроса, даже не поймут что происходит и спросят почему данные "старые"

2021-02-06 11:46 UTC, MarshalX approved these changes

2021-02-06 11:51 UTC, merged