Получение данных о лейбле
MarshalX/yandex-music-api pull request #525
Opened 2022-06-30 11:02 UTC by 1Finder1

Добавил новые методы для класса `Client`:
- `get_label `- Возвращает основную информацию о лейбле
- `get_label_artists `- Возвращает список артистов лейбла
- `get_label_albums `- Возвращает альбомы лейбла

2022-06-30 11:35 UTC, MarshalX commented
Первое что бросается в глаза -- произошла замена всех одинарных кавычек на двунарные. Так произошло потому что вы запустили black без указания конфига проект (файл black.toml в корне)

```shell
black --config black.toml ...
```

Так должно нормально отформатировать. Только вот вряд ли уже вернёт обратно одинарные кавычки. Зато не будет трогать их при следующем форматировании

2022-07-01 07:30 UTC, MarshalX requested changes
в этом ПРе полностью отсутвует обновленный async client, хотя есть async сокращения. Которые работать не будут. надо запустить скрипт "generate_async_version.py" и файл будет обновлен

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/label/label.py
> +        data['name'] = data.get('name')
id, name и прочие поля это примитивы. Их не нужно тут перечислять. Они десериализуются сами в super().de_json()

всё что тут надо перечислять это вложенность других моделей

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/label/label.py
> +        client.get_label_artists(label_id)
self.id*

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/label/label.py
> +        client.get_label_albums(label_id)
и тут, и ниже тоже

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/label/label.py
> +            :obj:`yandex_music.Label`: Label.
return не Label

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/label/label.py
> +    def de_json(cls, data: dict, client: 'Client') -> Optional['Label']:
тайпхинт возвращаемого значения не тот

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/label/label.py
> +        return cls(client=client, **data)
нет псевдонимов у методов модели

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/label/label.py
> +    """Класс, представляющий лейбл
точка в конце

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/client.py
> +        Получение информации о лейбле.
что-то с переносами строк

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/client.py
> +            timeout:
дубликат timeout арга

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/client.py
> +            :obj:`yandex_music.Label` | :obj:`None`: Лейбл :obj:`None`.
не тот тип

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/client.py
> +        for page in range(1, pages):
нет, мы не делаем циклы внутри методов client. потому что запросы могут захотеть слать в разных тредах и т.д. и т.п.

мы не навязываем то как вызывать методы разработчикам использующим нашу библиотеку

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/client.py
> +        for page in range(1, pages):
вместо этого у метода должен быть просто аргумент page которого я не вижу

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/client.py
> +            'play-id': play_id or "",
двойные кавычки

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/client.py
> +                'Гражданская абарона' будет исправлен на 'Гражданская оборона'.
тут кавычки в доке, а не в коде. тут двойные)

2022-07-01 07:30 UTC, MarshalX commented on yandex_music/client.py
> +        """Поставить отметку 'Мне нравится' треку/трекам.
кавычки

2022-07-01 08:34 UTC, MarshalX commented
> У меня возникает ошибка при запуске файла "generate_async_version.py":

https://github.com/MarshalX/yandex-music-api/commit/614d08cfdcbee55247ddfc371588e9f08c7ae83d

2022-07-01 08:36 UTC, MarshalX commented
Ещё вспомнил. Документация не сгенерирована. Подробнее тут: https://github.com/MarshalX/yandex-music-api/blob/main/CONTRIBUTING.md#%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F

Да, в репо меня нет .BAT'ника для винды. Можно ручками команды из Make выполнить в командой строке

2022-07-05 07:43 UTC, MarshalX commented
Если какие-то фиксы уже готовы, то надо бы порезолвить мои комментарии. Непонятно просто что исправлено, а что нет

2022-07-05 07:50 UTC, 1Finder1 commented
Я шёл по списку. Так что я исправил всё

2022-07-05 07:54 UTC, MarshalX commented
ну тогда плохие новости. во-первых вон упал black workflow. значит не прошло валидацию форматирования. во-вторых если открыть изменения pull request'a, то там всё еще куча изменений кавычек с одинарных на двунарные

2023-11-17 21:56 UTC, closed without merging