close #495
MarshalX/yandex-music-api pull request #535
Opened 2022-08-03 15:42 UTC by semen603089

Асинхронный клиент добавил
Блэк поправил 
Ветку сделал от dev к dev

2022-08-03 16:03 UTC, MarshalX requested changes
close стоит писать не в заголовке ПРа, а в содержимом

2022-08-03 16:03 UTC, MarshalX commented on yandex_music/client.py
> +        timeout (:obj:`int` | :obj:`float`, optional): Если это значение указано, используется как время ожидания
беды с оступами в доке

2022-08-03 16:03 UTC, MarshalX commented on yandex_music/client.py
> +    def children_landing_catalogue(self, timeout: Union[int, float] = None, *args, **kwargs):
нет тайп хинта на return

2022-08-03 16:03 UTC, MarshalX commented on yandex_music/client.py
> +        :obj:`yandex_music.LandingList`: Список контента.
дока врет. в коде возварщается другое

2022-08-03 16:03 UTC, MarshalX commented on yandex_music/client.py
> +        url = f"{self.base_url}/children-landing/catalogue"
по форматированию не собоюдены пустые строки как в других методах

2022-08-03 16:03 UTC, MarshalX commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
судя по файлу в issue сервер отдает объект в result. Почему тут массив не очень ясно

2022-08-03 16:12 UTC, semen603089 commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
ну там в blocks много объектов
я так понимаю их нужно распарсить в список
можно просто objects отдавать в принципе

2022-08-03 16:16 UTC, semen603089 commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
ну точнее objects["result"]

2022-08-03 16:29 UTC, semen603089 commented on yandex_music/client.py
> +        timeout (:obj:`int` | :obj:`float`, optional): Если это значение указано, используется как время ожидания
Беды пофиксил

2022-08-03 16:31 UTC, semen603089 commented on yandex_music/client.py
> +        url = f"{self.base_url}/children-landing/catalogue"
теперь соблюдены

2022-08-03 16:33 UTC, semen603089 commented on yandex_music/client.py
> +    def children_landing_catalogue(self, timeout: Union[int, float] = None, *args, **kwargs):
добавил

2022-08-03 16:34 UTC, semen603089 commented on yandex_music/client.py
> +        :obj:`yandex_music.LandingList`: Список контента.
сделал dict
не очень понятно когда может вернуть строку

2022-08-03 16:48 UTC, MarshalX requested changes

2022-08-03 16:48 UTC, MarshalX commented on yandex_music/client.py
> +        return result
а куда модель делать?

2022-08-03 16:48 UTC, MarshalX commented on yandex_music/client.py
> +    def children_landing_catalogue(self, timeout: Union[int, float] = None, *args, **kwargs) -> dict | str:
не дикт или строка. а модель возвращаться будет

2022-08-03 16:48 UTC, MarshalX commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
модель из трех полей, одно из которых blocks - массив блоков. модель блоков уже есть. есть ли модель из этих трех полей не помню

2022-08-04 05:10 UTC, semen603089 commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
Ну да, я пытаюсь сделать с Block.de_list(result["blocks"], self)
Это логично
Но в этом методе он по доке принимает "data (:obj:`list`): Список словарей с полями и значениями десериализуемого объекта." И у меня действительно список
Но type-hint у data - dict
И методы используются для словаря 
Так что вот тут то и не понятно

2022-08-04 05:33 UTC, semen603089 commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
То есть я передаю список блоков в метод который как я понял это и делает, но там ошибка вылетает 
Пока что я думаю почему
но проблема в 
  File "/yandex-music-api/yandex_music/landing/block_entity.py", line 71, in de_json
    data['data'] = de_json.get(data.get('type'))(data.get('data'), client)
TypeError: 'NoneType' object is not callable

2022-08-04 05:45 UTC, semen603089 commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
Понятно что возвращать это должно List[Block]
метод return [Block.de_json(row, self) for row in result.get("blocks")] тоже не работает по той же ошибке
Вполне вероятно что я что то не так понял просто с этими моделями

2022-08-04 06:41 UTC, MarshalX commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
словарь возвращает обертка над requests. поэтому там тайп хинт dict

2022-08-04 06:44 UTC, MarshalX commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
судя по ответу сервера у энтити блока есть type, однако такой, которого в библиотеке никогда не было. нужно "зарегитрировать" новый тип для десериализации тут https://github.com/MarshalX/yandex-music-api/blob/a30082f4929e56381c870cb03103777ae29bcc6b/yandex_music/landing/block_entity.py#L18

2022-08-04 06:45 UTC, MarshalX commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
там на ряду с type=album есть еще  `"type":"album-timed-show",`

2022-08-04 06:46 UTC, MarshalX commented on yandex_music/client.py
> +        return [LandingList.de_json(row, self) for row in objects['blocks']]
еще тип station есть. Тоже обработать надо

2022-08-21 19:34 UTC, closed without merging