Добавил функции для получения фалов в байтах
MarshalX/yandex-music-api pull request #541
Opened 2022-09-23 01:02 UTC by LulzLoL231

Closes #539

2022-09-23 06:57 UTC, MarshalX commented on yandex_music/utils/request.py
> +    def download_bytes(self, url, timeout=5, *args, **kwargs) -> bytes:
Извините, не совсем понял а зачем нам в `request` метод `download bytes`?) это ведь тоже самое что и `retrieve`. Я представлял себе что именно этот метод и будет использоваться в моделях у `download_bytes`

2022-09-23 07:00 UTC, MarshalX commented on yandex_music/__init__.py
> +__version__ = '2.1'
Если обновилась версия, то, наверное, и список изменений с 2.0.1 обновить надо было 😅 сравнить с main веткой

2022-09-24 02:46 UTC, LulzLoL231 commented on yandex_music/utils/request.py
> +    def download_bytes(self, url, timeout=5, *args, **kwargs) -> bytes:
Действительно, наверное гнался за более ясным названием функции.

2022-09-24 03:18 UTC, LulzLoL231 commented on yandex_music/__init__.py
> +__version__ = '2.1'
Сделал в https://github.com/MarshalX/yandex-music-api/pull/541/commits/fc46e574280c0e2a0904a242354e419010769ef9

2022-09-26 07:32 UTC, MarshalX requested changes
Кроме дублирования кода больше замечаний нет, спасибо. Я конечно могу принять текущий вариант, но релизить версию до исправления дублирования не стану) иначе так и останется в проекте

2022-09-26 07:32 UTC, MarshalX commented on yandex_music/track/track.py
> +        for info in self.download_info:
Это ведь уже полное копирование куска кода с обычного метода download_async. Хорошо бы было вынести в отдельный метод, а не вот так в лоб...

2022-09-26 07:32 UTC, MarshalX commented on yandex_music/track/track.py
> +        for info in self.download_info:
дублирование кода

2022-09-26 07:32 UTC, MarshalX commented on yandex_music/icon.py
> +        return self.client.request.retrieve(self.get_url(size))
тут просто хочу обратить внимание, что есть специальный метод get_url. Именно так желательно сделать везде потому что теперь на каждый download по 4 версии метода и в каждом строка собирается самостоятельно

2022-09-26 07:32 UTC, MarshalX commented on yandex_music/artist/artist.py
> +        return self.client.request.retrieve(f'https://{self.og_image.replace("%%", size)}')
имхо пришло время вынести везде эти f-string с replace в отдельный метод) как это сделано в другом классе (я пинганул вас там). 4 f-strings в каждом download_трулала это уже перебор 😁

2022-10-13 20:26 UTC, LulzLoL231 commented on yandex_music/track/track.py
> +        for info in self.download_info:
Перенёс этот кусок в новосозданную функцию `track.get_specific_download_info` в коммите https://github.com/MarshalX/yandex-music-api/pull/541/commits/0e0a6d693ed2546a071ae3bd9fba8e0e696a7d9f

2022-10-13 20:26 UTC, LulzLoL231 commented on yandex_music/track/track.py
> +        for info in self.download_info:
Исправлено.

2022-10-13 21:06 UTC, LulzLoL231 commented on yandex_music/artist/artist.py
> +        return self.client.request.retrieve(f'https://{self.og_image.replace("%%", size)}')
Перенёс все f-строки в отдельные функции формата `obj.get_cover_url` и т.п. в коммите https://github.com/MarshalX/yandex-music-api/pull/541/commits/7991a88ddcf672ea01a0eaa576c38211fb8e3f99

2022-10-13 21:06 UTC, LulzLoL231 commented on yandex_music/icon.py
> +        return self.client.request.retrieve(self.get_url(size))
Исправил.

2022-10-16 12:57 UTC, MarshalX approved these changes
Не без огрехов конечно. Например, напрочь были забыты алиасы для camelCase. Но уже приму и сам поправлю. Спасибо за вклад!

2022-10-16 12:58 UTC, merged