#509 Поля класса Status
MarshalX/yandex-music-api pull request #561
Opened 2022-11-05 18:24 UTC by andrew097

Добавлены поля pretrial_active, masterhub, has_options, userhash классу Status.

2022-11-06 14:16 UTC, andrew097 commented
Ошибки исправил, на чем black падал

2022-11-06 18:13 UTC, MarshalX requested changes
Спасибо большое за интерес к библиотеке. Исправьте пожалуйста пару моментов и предоставьте пример значений что приходят от сервера

2022-11-06 18:13 UTC, MarshalX commented on tests/test_status.py
> +    has_options = None
Было бы супер указать тестовые данные которые приходят в ответ на запрос. Вместо None и пустой строки

2022-11-06 18:13 UTC, MarshalX commented on yandex_music/account/status.py
> +        masterhub (:obj:'dict'): Словарь активных и доступных подписок пользователя TODO
А можно, пожалуйста, пример словаря? Возможно там стоит создавать новую модель?

2022-11-06 18:13 UTC, MarshalX commented on yandex_music/account/status.py
> +        userhash (:obj:'str'): Хэш-код идентификатора пользователя TODO
Я думаю в этой и строчке выше можно убрать TODO и поставить точку в конце

2022-11-06 18:13 UTC, MarshalX commented on yandex_music/account/status.py
> +    userhash: Optional[str] = ''
Значение по умолчанию у строки тоже None, не пустая

2022-11-06 18:14 UTC, MarshalX commented on yandex_music/account/status.py
> +        masterhub (:obj:'dict'): Словарь активных и доступных подписок пользователя TODO
А, забыл упомянуть. Обычно поле client что в документации, что в модели, всегда стоит самым последним. Так исторически сложилось)

2022-11-07 01:36 UTC, andrew097 commented on yandex_music/account/status.py
> +        masterhub (:obj:'dict'): Словарь активных и доступных подписок пользователя TODO
> 
'masterhub': {'active_subscriptions': [], 'available_subscriptions': []}

2022-11-07 01:38 UTC, andrew097 commented on yandex_music/account/status.py
> +        userhash (:obj:'str'): Хэш-код идентификатора пользователя TODO
В этой строчке - это 34? Тогда TODO убираю из 33, 34 или и в 32 тоже?

2022-11-07 03:33 UTC, andrew097 commented on tests/test_status.py
> +    has_options = None
`masterhub = {'active_subscriptions': [], 'available_subscriptions': []}`
`has_options = []`
Этого здесь достаточно будет же?

2022-11-07 09:01 UTC, MarshalX commented on yandex_music/account/status.py
> +        masterhub (:obj:'dict'): Словарь активных и доступных подписок пользователя TODO
Понял, спасибо. Тогда следует завести отдельную модель с двумя этими полями и в de_json прописать что masterhub это наша новая модель

2022-11-07 09:02 UTC, MarshalX commented on yandex_music/account/status.py
> +        userhash (:obj:'str'): Хэш-код идентификатора пользователя TODO
34 и 33 думаю да, а 32 нужно в любом случае будет переписать на отдельную модель. Это не будет словарем больше

2022-11-08 11:31 UTC, MarshalX commented on tests/test_status.py
> +    has_options = None
userhash тоже) чтобы иметь представление какого он формата. просто замените в своем userhash несколько символов и всё)

2022-11-08 11:41 UTC, MarshalX requested changes
Спасибо большое за исправления и новую модель. Нашёл несколько маленький несостыковок. Следует исправить

2022-11-08 11:41 UTC, MarshalX commented on yandex_music/account/masterhub.py
> +        active_subscriptions (:obj:`list`): Список активных подписок.
obj list из чего? Какой тип данных у листа. Как я понял из тестов там строки

2022-11-08 11:41 UTC, MarshalX commented on yandex_music/account/masterhub.py
> +    available_subscriptions: list = None
Следует указать из чего list. Еще у нас библиотека от Python 3.7. Кажется там еще нельзя было использовать стандартные типы как тайпхинты. Проверить плиз и, скорее всего, добавьте from typing import List... subs: List[str]

2022-11-08 11:41 UTC, MarshalX commented on yandex_music/account/masterhub.py
> +            :obj:`yandex_music.Status`: Информация об аккаунте пользователя.
> :obj:`yandex_music.Status`:

В методе возвращается MasterHub

2022-11-08 11:41 UTC, MarshalX commented on yandex_music/account/status.py
> +        has_options (:obj:'list'): Список подключенных опций аккаунта.
obj list из чего. следует указать примитив

2022-11-08 11:41 UTC, MarshalX commented on yandex_music/account/status.py
> +    has_options: Optional[list] = None
следует заменить list как уже писал выше

2022-11-08 11:41 UTC, MarshalX commented on tests/test_status.py
> +    userhash = ''
укажите пожалуйста пример значения userhash (заменив несколько символов в своем) и has options, если они вам известны

2022-11-08 11:41 UTC, MarshalX commented on yandex_music/account/status.py
> +        pretrial_active (:obj:`bool`, optional): TODO
если будете тут мимо проходить, то можно точку в конец доставить чтоб не выделялось сильно на фоне остальных

2022-11-08 11:41 UTC, MarshalX commented on yandex_music/account/status.py
> +        has_options (:obj:'list'): Список подключенных опций аккаунта.
ниже по коду все три новых поля опциональны. Судя по дкументации не везде указан optional. Нужно свести к чему-то одному

2022-11-08 12:39 UTC, andrew097 commented on yandex_music/account/masterhub.py
> +        active_subscriptions (:obj:`list`): Список активных подписок.
Я не могу сказать какие данные внутри. Мне вернулись пустые списки. Со строками в тестах видимо я зря

2022-11-08 12:45 UTC, andrew097 commented on yandex_music/account/status.py
> +        has_options (:obj:'list'): Список подключенных опций аккаунта.
По поводу списка, аналогично - у меня только пустой список.
Какие есть варианты разузнать?

2022-11-08 13:07 UTC, MarshalX commented on yandex_music/account/status.py
> +        has_options (:obj:'list'): Список подключенных опций аккаунта.
Ох( это уже сложнее... посмотрите в issues где я собрал отчеты пользователей о новых полях. Там есть в том числе и данные. Возможно там будут нужные для текущей задачи. Ишус закреплен

2022-11-08 13:26 UTC, MarshalX commented on yandex_music/account/status.py
> +        has_options (:obj:'list'): Список подключенных опций аккаунта.
Там тоже пустые списки. Очень грустно. Как бы там не было вложенной модели... она как бы уже существует. Называется Subscription

2022-11-08 13:27 UTC, MarshalX commented on yandex_music/account/status.py
> +        has_options (:obj:'list'): Список подключенных опций аккаунта.
Возможно стоит сделать запрос под аккаунтом без подписки и оно появится

2022-11-09 03:00 UTC, andrew097 commented on tests/test_status.py
> +    userhash = ''
has_options возвращает пустой List независимо от наличия подписки. Предлагаю оставить пока так

2022-11-09 03:02 UTC, andrew097 commented on yandex_music/account/masterhub.py
> +        active_subscriptions (:obj:`list`): Список активных подписок.
Также, независимо от подписки оба списка пустые. Без указания примитива же возможно использование?

2022-11-09 03:29 UTC, andrew097 commented on yandex_music/account/masterhub.py
> +    available_subscriptions: list = None
Вот так нормально будет?
`has_options: Optional[List[Any]] = None`

2022-11-09 11:14 UTC, MarshalX commented on yandex_music/account/masterhub.py
> +        active_subscriptions (:obj:`list`): Список активных подписок.
К сожалению я не вижу тогда смысла в добавлении этих полей если там будет Any. Представьте если там будет строка... чистого json'a... такое счастье только проблем создаст

2022-11-09 11:14 UTC, MarshalX commented on yandex_music/account/masterhub.py
> +    available_subscriptions: list = None
К сожалению я не вижу тогда смысла в добавлении этих полей если там будет Any. Представьте если там будет строка... чистого json'a... такое счастье только проблем создаст

2022-11-10 14:48 UTC, MarshalX requested changes
Одно маленькое замечание, а в остальном всё супер

2022-11-10 14:48 UTC, MarshalX commented on yandex_music/account/status.py
> +    pretrial_active: Optional[bool] = False
Для bool значение по умолчанию мы тоже ставим None. Всё же потому что False это точное отрицание, а None это неизвестное значение

2022-11-11 16:52 UTC, MarshalX approved these changes

2022-11-11 16:53 UTC, merged

2022-11-11 16:57 UTC, MarshalX commented
Спасибо!